baseurl = "https://cloud.gov"
languageCode = "en-us"
title = "cloud.gov"
pluralizelisttitles = "false"
publishdir = "public"

[params]
  email = "cloud-gov-inquiries@gsa.gov"
  description = "cloud.gov documentation"
  author = "18f"

  [params.analytics]
    [params.analytics.google]
      code = "UA-48605964-34"
    [params.analytics.dap]
      agency = "GSA"
      subagency = "18F"

[blackfriday]
  plainIDAnchors = true


[[menu.overview]]
    name = "Overview"
    identifier = "overview"
    weight = -120
[[menu.overview]]
    name = "Pricing"
    identifier = "pricing"
    weight = -115
[[menu.overview]]
    name = "Security"
    identifier = "security"
    weight = -110
[[menu.overview]]
    name = "Technology"
    identifier = "technology"
    weight = -105
[[menu.overview]]
    name = "Terminology"
    identifier = "terminology"
    weight = -100

[[menu.docs]]
    name = "Getting Started"
    identifier = "getting-started"
    pre = "<i class='fa fa-road fa-fw'></i>"
    weight = -120
[[menu.docs]]
    name = "Deploying Apps"
    identifier = "apps"
    pre = "<i class='fa fa-file-text fa-fw'></i>"
    weight = -110
[[menu.docs]]
    name = "Services"
    identifier = "services"
    pre = "<i class='fa fa-fw fa-database'></i>"
    weight = -100
[[menu.docs]]
    name = "Advanced"
    identifier = "advanced"
    pre = "<i class='fa fa-rocket fa-fw'></i>"
    weight = -100
[[menu.docs]]
    name = "Experimental Features"
    identifier = "experimental"
    pre = "<i class='fa fa-flask fa-fw'></i>"
    weight = -90

[[menu.docs]]
    name = "Contributing"
    identifier = "ops"
    pre = "<i class='fa fa-fw fa-wrench'></i>"
[[menu.docs]]
    name = "Deployment"
    identifier = "deployment"
    parent = "ops"
[[menu.docs]]
    name = "Tenants"
    identifier = "tenants"
    parent = "ops"
[[menu.docs]]
    name = "Operations"
    identifier = "operations"
    parent = "ops"
